server:
  port: 8999

eureka:
  host: localhost:8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true


spring:
  application:
    name: unitech-app
  datasource:
    url: jdbc:postgresql://vmi1229865.contaboserver.net:5439/unitech?useUnicode=true&&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
