server:
  port: 8761

spring:
  application:
    name: oneamz-eureka-server

logging:
  level:
    web: debug

eureka:
  host: localhost:8761
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.host}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000